# Chinese Navigation Menu (中文导航菜单)
main:
  - name: 主页
    url: /zh/
    weight: 1
  - name: 研究方向
    url: /zh/research/
    weight: 2
  - name: 团队成员
    url: /zh/people/
    weight: 3
  - name: 研究成果
    url: /zh/publications/
    weight: 4
  - name: 新闻动态
    url: /zh/news/
    weight: 5
  - name: 研究资源
    url: /zh/resources/
    weight: 6
  - name: 加入我们
    url: /zh/join-us/
    weight: 7
