[[main]]
  name = "Home"
  url = "/"
  weight = 1
[[main]]
  name = "Research"
  url = "/research/"
  weight = 2
[[main]]
  name = "People"
  url = "/people/"
  weight = 3
[[main]]
  name = "Publications"
  url = "/publications/"
  weight = 4
[[main]]
  name = "Resources"
  url = "/resources/"
  weight = 5
[[main]]
  name = "Join Us"
  url = "/join-us/"
  weight = 6
