baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Yuzhang Neuro+AI Lab'

# Enable analytics
enableAnalytics = true

# Enable search
enableSearch = true

# Enable dark mode
day_night = true

# Default language
defaultContentLanguage = "en"
hasCJKLanguage = true

# Improve SEO
enableRobotsTXT = true
canonifyURLs = true

# Improve performance
enableGitInfo = true
enableEmoji = true
